// <auto-generated />
using CleanArchitecture.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CleanArchitecture.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502000000_AddClubSupporterSystem")]
    partial class AddClubSupporterSystem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
